name: 'spring-boot-microservices-course'
services:
  catalog-service:
    image: nilarebecca/bookstore-catalog-service
    container_name: catalog-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DB_URL=jdbc:postgresql://catalog-db:5432/postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
    ports:
      - "7071:7071"
    restart: unless-stopped
    depends_on:
      catalog-db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 700m
    labels:
      logging: "promtail"

  order-service:
    image: nilarebecca/bookstore-order-service
    container_name: order-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - ORDERS_CATALOG_SERVICE_URL=http://api-gateway:8989/catalog
      - DB_URL=jdbc:postgresql://orders-db:5432/postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - RABBITMQ_HOST=bookstore-rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
      - OAUTH2_SERVER_URL=http://keycloak:9191
      - SWAGGER_API_GATEWAY_URL=http://api-gateway:8989/orders
      - MANAGEMENT_TRACING_ENABLED=${MANAGEMENT_TRACING_ENABLED}
      - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://tempo:9411
    ports:
      - "7072:7072"
    restart: unless-stopped
    depends_on:
      orders-db:
        condition: service_healthy
      bookstore-rabbitmq:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 700m
    labels:
      logging: "promtail"
  notification-service:
    image: nilarebecca/bookstore-notification-service
    container_name: notification-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DB_URL=jdbc:postgresql://notifications-db:5432/postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - RABBITMQ_HOST=bookstore-rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
      - MAIL_HOST=mailhog
      - MAIL_PORT=1025
      - MANAGEMENT_TRACING_ENABLED=${MANAGEMENT_TRACING_ENABLED}
      - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://tempo:9411
    ports:
      - "7073:7073"
    restart: unless-stopped
    depends_on:
      notifications-db:
        condition: service_healthy
      bookstore-rabbitmq:
        condition: service_healthy
      mailhog:
        condition: service_started
    deploy:
      resources:
        limits:
          memory: 700m
    labels:
      logging: "promtail"