name: 'spring-boot-microservices-course'
services:
  catalog-service:
    image: nilarebecca/bookstore-catalog-service
    container_name: catalog-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DB_URL=jdbc:postgresql://catalog-db:5432/postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
    ports:
      - "7071:7071"
    restart: unless-stopped
    networks:
      - bookstore-network
#    depends_on:
#      catalog-db:
#        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 700m
    labels:
      logging: "promtail"

  order-service:
    image: nilarebecca/bookstore-order-service
    container_name: order-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - ORDERS_CATALOG_SERVICE_URL=http://api-gateway:7979/catalog
      - DB_URL=jdbc:postgresql://orders-db:5432/postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - RABBITMQ_HOST=bookstore-rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
      - OAUTH2_SERVER_URL=http://keycloak:9191
      - SWAGGER_API_GATEWAY_URL=http://api-gateway:7979/orders
      #- MANAGEMENT_TRACING_ENABLED=${MANAGEMENT_TRACING_ENABLED}
      #- MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://tempo:9411
    ports:
      - "7072:7072"
    restart: unless-stopped
    networks:
      - bookstore-network
#    depends_on:
#      orders-db:
#        condition: service_healthy
#      bookstore-rabbitmq:
#        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 700m
    labels:
      logging: "promtail"
  notification-service:
    image: nilarebecca/bookstore-notification-service
    container_name: notification-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DB_URL=jdbc:postgresql://notifications-db:5432/postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - RABBITMQ_HOST=bookstore-rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
      - MAIL_HOST=mailhog
      - MAIL_PORT=1025
      #- MANAGEMENT_TRACING_ENABLED=${MANAGEMENT_TRACING_ENABLED}
      #- MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://tempo:9411
    ports:
      - "7073:7073"
    restart: unless-stopped
    networks:
      - bookstore-network
#    depends_on:
#      notifications-db:
#        condition: service_healthy
#      bookstore-rabbitmq:
#        condition: service_healthy
#      mailhog:
#        condition: service_started
    deploy:
      resources:
        limits:
          memory: 700m
    labels:
      logging: "promtail"
  api-gateway:
    image: nilarebecca/bookstore-api-gateway
    container_name: api-gateway
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - CATALOG_SERVICE_URL=http://catalog-service:7071
      - ORDER_SERVICE_URL=http://order-service:7072
      - MANAGEMENT_TRACING_ENABLED=${MANAGEMENT_TRACING_ENABLED}
      - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://tempo:9411
    ports:
      - "7979:7979"
    restart: unless-stopped
    networks:
      - bookstore-network
    deploy:
      resources:
        limits:
          memory: 700m
    labels:
      logging: "promtail"

  bookstore-webapp:
    image:  nilarebecca/bookstore-webapp
    container_name: bookstore-webapp
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - BOOKSTORE_API_GATEWAY_URL=http://api-gateway:7979
      - OAUTH2_SERVER_URL=http://keycloak:9191
      - MANAGEMENT_TRACING_ENABLED=${MANAGEMENT_TRACING_ENABLED}
      - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://tempo:9411
    ports:
      - "7070:7070"
    restart: unless-stopped
    networks:
      - bookstore-network
    deploy:
      resources:
        limits:
          memory: 700m
    labels:
      logging: "promtail"

networks:
  bookstore-network:
    external: true